---
title: "MotifVBias"
output: html_document
date: "2026-04-07"
---
```{r setup, include=FALSE}


knitr::opts_knit$set(root.dir = "Path/To/DataFolder") # rmarkdown will otherwise default to the folder where the script is
```
```{r}

Models=readRDS("./MACOptimalModelExpSets.rds")
RepModels=readRDS("./MACRepSetHMMs.rds")
MACVitRep=readRDS("./RepSetViterbis.rds")
MACRepPUS=readRDS("./MACUnionsRepSet.rds")
MACViterbis=readRDS("./MACViterbis.rds")
Unions=readRDS("./MACUnions.rds")
RepMotThresh=readRDS("./RepMotThresh.rds")
ExpMotThresh=readRDS("./ExpMotThresh.rds")
RepMotGC=readRDS("./RepMotGC.rds")
ExpMotGC=readRDS("./ExpMotGC.rds")
set.seed(234)
library(ggplot2)
library(mgcv)
beng=c()
RepSignals=readRDS("/Users/oliverhughes/Downloads/DataFolder/RepSignalExp.rds")
OneState=c()
for(i in 1:length(RepSignals)){
  if(is.null(nrow(RepSignals[[i]]))){
    next
  }
 Frame=RepSignals[[i]]
  One=c()
  for(j in 1:ncol(Frame)){
    One[j]=exp(mean(log(Frame[,j])))
  }
  names(One)=as.character(c(1:ncol(Frame)))
  OneState[[i]]=One
}
names(OneState)=names(RepSignals)

Comparison=c("(Replicate Sets) Motif Enrichment vs Bias Severity","(Experiment Sets) Motif Enrichment vs Bias Severity","(Replicate Sets) Motif Enrichment vs Signal","(Experimet Sets) Motif Enrichment vs Signal")
Proportion=c()
Correlation=c()
AbsCorrelation=c()
ProportionP=c()
CorrelationP=c()
AbsCorrelationP=c()
```
(Replicate Sets) Motif Enrichment vs Bias Severity
```{r}

Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(RepMotThresh)){
  if(("None"%in%RepMotThresh[[i]])){
     next
   }

  if(!names(RepMotThresh)[i]%in%names(RepContrasts)){
    next
  }
    #if(names(RepMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(RepMotThresh[[i]])){
  #  next
  #}
  Mots=as.numeric(unlist(RepMotThresh[[i]]))
  Sig=as.numeric(unlist(((RepContrasts[names(RepContrasts)==names(RepMotThresh)[i]]))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
  if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)<2){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  if(sum(Mots==0.001)==length(Mots)){
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))==1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)

Proportion[1]=sum(TotalRepDiffFrame$Hit)
Correlation[1]=cor(TotalRepDiffFrame$Diff,TotalRepDiffFrame$Sig)
AbsCorrelation[1]=cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method = "spearman")
```
```{r}
fit <- lm(Diff ~ Sig, data = TotalRepDiffFrame)
pred <- predict(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")

ggplot(TotalRepDiffFrame, aes(x=Sig, y=Diff)) + 
  geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit))
  xlim(-1.5,1.5)
  
  
  fit <- lm(Diff ~ Sig, data = TotalRepDiffFrame)
pred <- predict(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")

ggplot(TotalRepDiffFrame, aes(x=Sig, y=Diff)) + 
  geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit))
  xlim(-1.5,1.5)
  
  TotalRepDiffFrame$Diff=abs(TotalRepDiffFrame$Diff)
  fit <- gam(Hit ~ s(Diff), data = TotalRepDiffFrame, family = binomial)
pred <- predict.gam(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")
ggplot(TotalRepDiffFrame, aes(x=abs(Diff), y=Hit)) + 
   #geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit)) 




```
```{r}
Stat1=c()
Stat2=c()
Stat3=c()
for(k in 1:10000){  
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(RepMotThresh)){

    if(("None"%in%RepMotThresh[[i]])){
     next
   }
  
  
  if(!names(RepMotThresh)[i]%in%names(RepContrasts)){
    next
  }
    #if(names(RepMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(RepMotThresh[[i]])){
  #  next
  #}
  Mots=(as.numeric(unlist(RepMotThresh[[i]])))
  Sig=(as.numeric(unlist(((RepContrasts[names(RepContrasts)==names(RepMotThresh)[i]])))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
 if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  Mots=sample(Mots)
  Sig=sample(Sig)
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))==1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)
  #geom_point(position=position_jitter(1,3), pch=21, fill="#FF0000AA") +



Stat1[k]=sum(TotalRepDiffFrame$Hit)
Stat2[k]=cor(TotalRepDiffFrame$Diff,TotalRepDiffFrame$Sig)
Stat3[k]= abs(cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method="spearman"))
}


ProportionP[1]=sum(abs(nrow(TotalRepDiffFrame)/2-Stat1)>abs((nrow(TotalRepDiffFrame)/2-Proportion[1])))/length(Stat1)
CorrelationP[1]=sum(abs(Stat2)>abs(Correlation[1]))/length(Stat2)
AbsCorrelationP[1]=sum(abs(Stat3)>abs(AbsCorrelation[1]))/length(Stat3)
```
(Experiment Sets) Motif Enrichment vs Bias Severity
```{r}

Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(ExpMotThresh)){
  if(("None"%in%ExpMotThresh[[i]])){
     next
   }

  if(!names(ExpMotThresh)[i]%in%names(ExpContrasts)){
    next
  }
    #if(names(ExpMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(ExpMotThresh[[i]])){
  #  next
  #}
  Mots=as.numeric(unlist(ExpMotThresh[[i]]))
  Sig=as.numeric(unlist(((ExpContrasts[names(ExpContrasts)==names(ExpMotThresh)[i]]))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
  if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)<2){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  if(sum(Mots==0.001)==length(Mots)){
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))==1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)

Proportion[2]=sum(TotalRepDiffFrame$Hit)
Correlation[2]=cor(TotalRepDiffFrame$Diff,TotalRepDiffFrame$Sig)
AbsCorrelation[2]=cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method = "spearman")
```
```{r}

  fit <- lm(Diff ~ Sig, data = TotalRepDiffFrame)
pred <- predict(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")

ggplot(TotalRepDiffFrame, aes(x=Sig, y=Diff)) + 
  geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit))

  xlim(-1.5,1.5)

   TotalRepDiffFrame$Diff=abs(TotalRepDiffFrame$Diff)
    fit <- gam(Hit ~ s(Diff), data = TotalRepDiffFrame, family = binomial)
pred <- predict.gam(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")
ggplot(TotalRepDiffFrame, aes(x=Diff, y=Hit)) + 
   #geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit)) 
```
```{r}

Stat1=c()
Stat2=c()
Stat3=c()
for(k in 1:10000){  
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(ExpMotThresh)){

    if(("None"%in%ExpMotThresh[[i]])){
     next
   }
  
  
  if(!names(ExpMotThresh)[i]%in%names(ExpContrasts)){
    next
  }
    #if(names(ExpMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(ExpMotThresh[[i]])){
  #  next
  #}
  Mots=(as.numeric(unlist(ExpMotThresh[[i]])))
  Sig=(as.numeric(unlist(((ExpContrasts[names(ExpContrasts)==names(ExpMotThresh)[i]])))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
 if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  Mots=sample(Mots)
  Sig=sample(Sig)
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))==1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)
  #geom_point(position=position_jitter(1,3), pch=21, fill="#FF0000AA") +



Stat1[k]=sum(TotalRepDiffFrame$Hit)
Stat2[k]=cor(TotalRepDiffFrame$Diff,TotalRepDiffFrame$Sig)
Stat3[k]= abs(cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method="spearman"))
}


ProportionP[2]=sum(abs(nrow(TotalRepDiffFrame)/2-Stat1)>abs((nrow(TotalRepDiffFrame)/2-Proportion[2])))/length(Stat1)
CorrelationP[2]=sum(abs(Stat2)>abs(Correlation[2]))/length(Stat2)
AbsCorrelationP[2]=sum(abs(Stat3)>abs(AbsCorrelation[2]))/length(Stat3)




```
(Replicate Sets) Motif Enrichment vs ChIP Signal
```{r}
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(RepMotThresh)){
  if(("None"%in%RepMotThresh[[i]])){
     next
   }

  if(!names(RepMotThresh)[i]%in%names(OneState)){
    next
  }
    #if(names(RepMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(RepMotThresh[[i]])){
  #  next
  #}
  Mots=as.numeric(unlist(RepMotThresh[[i]]))
  Sig=as.numeric(unlist(((OneState[names(OneState)==names(RepMotThresh)[i]]))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
  if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  if(sum(RepMotThresh[[i]]==0.001)==length(RepMotThresh[[i]])){
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))!=1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)

Proportion[3]=sum(TotalRepDiffFrame$Hit)

AbsCorrelation[3]=cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method = "spearman")

```
```{r}

Stat1=c()
Stat3=c()
for(k in 1:10000){  
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(RepMotThresh)){

    if(("None"%in%RepMotThresh[[i]])){
     next
   }
  
  
  if(!names(RepMotThresh)[i]%in%names(OneState)){
    next
  }
    #if(names(RepMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(RepMotThresh[[i]])){
  #  next
  #}
  Mots=(as.numeric(unlist(RepMotThresh[[i]])))
  Sig=(as.numeric(unlist(((OneState[names(OneState)==names(RepMotThresh)[i]])))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
 if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  Mots=sample(Mots)
  Sig=sample(Sig)
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))!=1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)
  #geom_point(position=position_jitter(1,3), pch=21, fill="#FF0000AA") +



Stat1[k]=sum(TotalRepDiffFrame$Hit)
Stat3[k]= abs(cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method="spearman"))
}

ProportionP[3]=sum(abs(nrow(TotalRepDiffFrame)/2-Stat1)>abs((nrow(TotalRepDiffFrame)/2-Proportion[3])))/length(Stat1)
AbsCorrelationP[3]=sum(abs(Stat3)>abs(AbsCorrelation[3]))/length(Stat3)



```
```{r}

beng=c()
RepSignals=readRDS("/Users/oliverhughes/Downloads/DataFolder/ExpSignals.rds")

OneState=c()
for(i in 1:length(RepSignals)){
  if(is.null(nrow(RepSignals[[i]]))){
    next
  }
 Frame=RepSignals[[i]]
  One=c()
  for(j in 1:ncol(Frame)){
    One[j]=exp(mean(log(Frame[,j])))
  }
  names(One)=as.character(c(1:ncol(Frame)))
  OneState[[i]]=One
}
names(OneState)=names(RepSignals)



```
(Experiment Sets) Motif Enrichment vs ChIP Signal

```{r}
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(ExpMotThresh)){
  if(("None"%in%ExpMotThresh[[i]])){
     next
   }

  if(!names(ExpMotThresh)[i]%in%names(OneState)){
    next
  }
    #if(names(ExpMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(ExpMotThresh[[i]])){
  #  next
  #}
  Mots=as.numeric(unlist(ExpMotThresh[[i]]))
  Sig=as.numeric(unlist(((OneState[names(OneState)==names(ExpMotThresh)[i]]))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
  if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)<2){
    next
  }
  if(sum(Mots==0.001)==length(Mots)){
    next
    }
  if(length(Mots)!=length(Sig)){
    print(i)
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
    

  Sig[Sig==0]=min(Sig[Sig!=0])/10
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))!=1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)

Proportion[4]=sum(TotalRepDiffFrame$Hit)
AbsCorrelation[4]=cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method = "spearman")

```
```{r}

  fit <- lm(Diff ~ Sig, data = TotalRepDiffFrame)
pred <- predict(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")

ggplot(TotalRepDiffFrame, aes(x=Sig, y=Diff)) + 
  geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit))

   TotalRepDiffFrame$Diff=abs(TotalRepDiffFrame$Diff)
    fit <- gam(Hit ~ s(Diff), data = TotalRepDiffFrame, family = binomial)
pred <- predict.gam(fit,TotalRepDiffFrame, type = "response", se=TRUE)
predframe=data.frame(pred$fit,pred$fit-pred$se.fit,pred$fit+pred$se.fit)
TotalRepDiffFrame$fit=pred$fit
TotalRepDiffFrame$Upper=pred$fit+pred$se.fit
TotalRepDiffFrame$Lower=pred$fit-pred$se.fit
names(predframe)=c("fit","upper","lower")
ggplot(TotalRepDiffFrame, aes(x=Diff, y=Hit)) + 
   #geom_point() +
  geom_ribbon(data = TotalRepDiffFrame, alpha = 0.3,
              aes(ymin = Lower, ymax = Upper, fill = "confidence interval")) +
  geom_line(data = TotalRepDiffFrame, aes(y=fit)) 

```
```{r}

Stat1=c()
Stat3=c()
for(k in 1:10000){  
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
Trumps=c()
Probs=c()
Totals=c()
MotDiff=c()
SigDiff=c()
for(i in 1:length(ExpMotThresh)){

    if(("None"%in%ExpMotThresh[[i]])){
     next
   }
  
  
  if(!names(ExpMotThresh)[i]%in%names(OneState)){
    next
  }
    #if(names(ExpMotThresh)[i]%in%Skips){
  #next
 # }
  #if(is.null(ExpMotThresh[[i]])){
  #  next
  #}
  Mots=(as.numeric(unlist(ExpMotThresh[[i]])))
  Sig=(as.numeric(unlist(((OneState[names(OneState)==names(ExpMotThresh)[i]])))))
  
  MotNA=which(is.na(Mots))
  SigNA=which(is.na(Sig))
 if(length(MotNA)+length(SigNA)>0){
  Mots=Mots[-c(MotNA,SigNA)]
  Sig=Sig[-c(MotNA,SigNA)]
  }
   if(sum(is.na(Mots))==length(Mots)){
    next
 }
 
  if(length(Sig)==0){
    next
  }
  if(length(Mots)==0){
    next
  }
  if(sum(is.na(Sig))>0){
    next
  }
  if(length(Mots)!=length(Sig)){
    print("Error, Sig and Mot Have Different Lengths")
    next
  }
  Sig[Sig==0]=min(Sig[Sig!=0])/10
  Mots=sample(Mots)
  Sig=sample(Sig)
  NPairs=expand.grid(Mots,Mots)
  NPairs$Raysh=abs(log2(NPairs$Var1/NPairs$Var2))
 
  Compo=c()
  Tracker=c()
  Diff=c()
  Sigi=c()
  for(j in 1:nrow(NPairs)){
    if(NPairs$Var1[j]==NPairs$Var2[j]){
      next
    }
    
    Moss1=Sig[Mots==NPairs$Var1[j]]
    Moss2=Sig[Mots==NPairs$Var2[j]]
    if(paste(c(Moss1,Moss2),collapse=" ")%in%Tracker){
      next
    }
    Compo[j]=((NPairs$Var1[j]>NPairs$Var2[j])+(Moss1>Moss2))!=1
    Sigi[j]=log(Moss1/Moss2)
    Diff[j]=(log(NPairs$Var1[j]/NPairs$Var2[j]))
    Tracker=c(Tracker,paste(c(Moss2,Moss1),collapse=" "))
  }
  SigDiff[i]=paste(na.omit(Sigi),collapse=" ")
  Trumps[i]=paste(na.omit(Compo),collapse=" ")
  Probs[i]=paste(na.omit(Compo),collapse=" ")
  MotDiff[i]=paste(na.omit(Diff),collapse=" ")
  Totals[i]=length(na.omit(Compo))
  
}
ExtrDiffFrame=data.frame(as.logical(unlist(strsplit(Probs,split=" "))),as.numeric(unlist(strsplit(MotDiff,split=" "))),as.numeric(unlist(strsplit(SigDiff,split=" "))))
names(ExtrDiffFrame)=c("Hit","Diff","Sig")

TotalRepDiffFrame=ExtrDiffFrame

TotalRepDiffFrame$Hit=as.numeric(TotalRepDiffFrame$Hit)
TotalRepDiffFrame$Diff=abs(TotalRepDiffFrame$Diff)
TotalRepDiffFrame=na.omit(TotalRepDiffFrame)
  #geom_point(position=position_jitter(1,3), pch=21, fill="#FF0000AA") +


Stat1[k]=sum(TotalRepDiffFrame$Hit)
Stat3[k]= abs(cor(abs(TotalRepDiffFrame$Diff),TotalRepDiffFrame$Hit,method="spearman"))
}


ProportionP[4]=sum(abs(nrow(TotalRepDiffFrame)/2-Stat1)>abs((nrow(TotalRepDiffFrame)/2-Proportion[4])))/length(Stat1)
AbsCorrelationP[4]=sum(abs(Stat3)>abs(AbsCorrelation[4]))/length(Stat3)

```


